/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projects;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Properties;

public class App {

    private static Connection createConnection()
            throws SQLException, ClassNotFoundException
    {
        Class.forName("com.exasol.jdbc.EXADriver");

        Properties props = new Properties();
        props.setProperty("user", "sys");
        props.setProperty("password", "exasol");
        props.setProperty("validateservercertificate", "0");
        return DriverManager.getConnection("jdbc:exa:127.0.0.1:45625", props);
    }

    public static void main(String[] args) throws SQLException, ClassNotFoundException {
        Connection conn1 = createConnection();
        System.out.println("connected");
    }
}
